In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("anime_data.csv")

In [4]:
df.head()

,anime_id,title,anime_type,source,episodes,status,aired_string,rating,score,rank,popularity,members,favorites,scored_by,duration_min,studios,genres,producers,synopsis
0,51818,Enen no Shouboutai: San no Shou,TV,Manga,12,Currently Airing,"Apr 5, 2025 to Jun 21, 2025",PG-13 - Teens 13 or older,7.93,772,1192,222393,1476,19050,24,David Production,Action|Fantasy|Sci-Fi,Mainichi Broadcasting System|Kodansha|DMM.com|...,Third season of Enen no Shouboutai.
1,56038,Lazarus,TV,Original,13,Currently Airing,"Apr 6, 2025 to ?",R - 17+ (violence & profanity),7.33,2703,1428,180636,1068,17995,23,MAPPA,Action|Suspense,Aniplex|dugout|Sola Entertainment,The year is 2052—an era of unprecedented peace...
2,59160,Wind Breaker Season 2,TV,Web manga,12,Currently Airing,"Apr 4, 2025 to Jun 20, 2025",PG-13 - Teens 13 or older,7.84,972,1705,145930,742,20381,23,CloverWorks,Action|Delinquents|School,Aniplex|Mainichi Broadcasting System|Kodansha|...,Second season of Wind Breaker.
3,59597,Witch Watch,TV,Manga,26,Currently Airing,"Apr 6, 2025 to ?",PG-13 - Teens 13 or older,7.48,2080,1966,121650,386,17259,24,Bibury Animation Studios,Comedy|Supernatural,Shogakukan-Shueisha Productions|Shochiku|Maini...,Nico Wakatsuki has finished her six years of w...
4,60146,"Saikyou no Ousama, Nidome no Jinsei wa Nani wo...",TV,Other,12,Currently Airing,"Apr 2, 2025 to Jun 18, 2025",PG-13 - Teens 13 or older,5.20,13130,2076,114162,977,23243,22,Studio A-CAT,Fantasy|Isekai|Reincarnation,Movic|Fuji TV|AT-X|KlockWorx|Slow Curve|Kansai...,The story follows the strongest king in histor...

In [6]:
df.columns

Index(['anime_id', 'title', 'anime_type', 'source', 'episodes', 'status',
       'aired_string', 'rating', 'score', 'rank', 'popularity', 'members',
       'favorites', 'scored_by', 'duration_min', 'studios', 'genres',
       'producers', 'synopsis'],
      dtype='str')

In [7]:
df.describe()

,anime_id,episodes,score,rank,popularity,members,favorites,scored_by,duration_min
count,7739.000000,7739.000000,7739.000000,7739.000000,7739.000000,7.739000e+03,7739.000000,7.739000e+03,7739.000000
mean,33172.386484,41.675539,5.433464,7722.623336,8305.822458,1.829002e+05,5004.539992,9.710739e+04,17.658095
std,20118.109319,137.860548,3.002387,6438.090930,7506.126484,4.564634e+05,25995.257733,2.749953e+05,9.169277
min,15.000000,0.000000,0.000000,0.000000,1.000000,2.400000e+01,0.000000,0.000000e+00,0.000000
25%,11740.000000,11.000000,5.480000,2098.000000,1894.500000,1.120000e+03,2.000000,1.855000e+02,10.000000
50%,36531.000000,13.000000,6.630000,6149.000000,5637.000000,1.647100e+04,53.000000,5.307000e+03,23.000000
75%,51386.500000,26.000000,7.420000,12247.500000,14077.000000,1.275550e+05,608.000000,5.179350e+04,24.000000
max,61764.000000,1818.000000,9.300000,21707.000000,28442.000000,4.169072e+06,238513.000000,2.938777e+06,59.000000

In [8]:
df.describe(include = "all")

,anime_id,title,anime_type,source,episodes,status,aired_string,rating,score,rank,popularity,members,favorites,scored_by,duration_min,studios,genres,producers,synopsis
count,7739.000000,7739,7739,7739,7739.000000,7739,7739,7664,7739.000000,7739.000000,7739.000000,7.739000e+03,7739.000000,7.739000e+03,7739.000000,6679,7728,7739,7734
unique,NaN,5142,6,17,NaN,3,3782,6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,794,1381,2636,4479
top,NaN,One Piece,TV,Manga,NaN,Finished Airing,"Oct 20, 1999 to ?",PG-13 - Teens 13 or older,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Toei Animation,Comedy,add some,No synopsis information has been added to this...
freq,NaN,64,6600,2368,NaN,6593,64,3736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,295,763,1929,835
mean,33172.386484,NaN,NaN,NaN,41.675539,NaN,NaN,NaN,5.433464,7722.623336,8305.822458,1.829002e+05,5004.539992,9.710739e+04,17.658095,NaN,NaN,NaN,NaN
std,20118.109319,NaN,NaN,NaN,137.860548,NaN,NaN,NaN,3.002387,6438.090930,7506.126484,4.564634e+05,25995.257733,2.749953e+05,9.169277,NaN,NaN,NaN,NaN
min,15.000000,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,0.000000,0.000000,1.000000,2.400000e+01,0.000000,0.000000e+00,0.000000,NaN,NaN,NaN,NaN
25%,11740.000000,NaN,NaN,NaN,11.000000,NaN,NaN,NaN,5.480000,2098.000000,1894.500000,1.120000e+03,2.000000,1.855000e+02,10.000000,NaN,NaN,NaN,NaN
50%,36531.000000,NaN,NaN,NaN,13.000000,NaN,NaN,NaN,6.630000,6149.000000,5637.000000,1.647100e+04,53.000000,5.307000e+03,23.000000,NaN,NaN,NaN,NaN
75%,51386.500000,NaN,NaN,NaN,26.000000,NaN,NaN,NaN,7.420000,12247.500000,14077.000000,1.275550e+05,608.000000,5.179350e+04,24.000000,NaN,NaN,NaN,NaN
max,61764.000000,NaN,NaN,NaN,1818.000000,NaN,NaN,NaN,9.300000,21707.000000,28442.000000,4.169072e+06,238513.000000,2.938777e+06,59.000000,NaN,NaN,NaN,NaN

In [ ]:
df.isnull().sum()

NameError: name 'df' is not defined

: